version: '3.9'

services:
  database:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    command: -p 5433
    ports:
    - 5433:5433
    volumes:
      - najitnajist_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: najitnajist

  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
      
volumes:
  najitnajist_db_data:
