export enum PocketbaseCollections {
  USERS = 'users',
  POSTS = 'posts',
  RECIPES = 'recipes',
  RECIPE_TYPES = 'recipe_types',
  RECIPE_RESOURCE_METRIC = 'recipe_resource_metric',
  USER_LIKED_POSTS = 'user_liked_posts',
  USER_LIKED_RECIPES = 'user_liked_recipes',
  RECIPE_DIFFICULTY = 'recipe_difficulty',
  POST_CATEGORIES = 'post_categories',
  CONTACT_FORM_REPLIES = 'contact_form_replies',
  USER_ADDRESSES = 'user_addresses',
  MUNICIPALITY = 'municipality',
  NEWSLETTER_SUBSCRIPTIONS = 'newsletter_subscriptions',
  PREVIEW_SUBSCRIBERS_TOKENS = 'preview_subscribers_tokens',

  PRODUCTS = 'products',
  PRODUCT_STOCK = 'product_stock',
  PRODUCT_PRICES = 'product_prices',
  PRODUCT_CATEGORIES = 'product_categories',
}
