import { Order } from '@najit-najist/api';

export const testOrder: Order = {
  id: 'test',
  address_city: 'City',
  address_houseNumber: '12',
  address_municipality: {
    created: new Date(),
    id: 'test',
    name: 'Hradec Kralové',
    slug: 'hradec-kralove',
  },
  address_postalCode: '50801',
  address_streetName: 'Jičín',
  created: new Date(),
  email: 'test@example.com',
  firstName: 'Otaka',
  lastName: 'Shimada',
  delivery_method_price: 200,
  payment_method_price: 0,
  payment_method: {
    created: new Date(),
    description: 'sdfds',
    except_delivery_methods: [],
    id: 'id',
    name: 'Převodem na účet',
    payment_on_checkout: false,
    price: 200,
    notes: 'asdfaodsjfoadsjfoasdj',
  },
  products: [
    {
      count: 2,
      created: new Date(),
      id: 'product-id',
      order: 1,
      totalPrice: 400,
      product: {
        created: new Date(),
        id: 'newItem',
        images: [],
        name: 'Produkt moc dlouhy',
        slug: '/produkt',
        stock: {
          count: 1,
          created: new Date(),
          id: 'sdfsd',
        },
        price: { discount: null, created: new Date(), id: 'id', value: 100 },
      },
    },
    {
      count: 2,
      created: new Date(),
      id: 'product-id-2',
      order: 1,
      totalPrice: 400,
      product: {
        created: new Date(),
        id: 'newItem',
        images: [],
        name: 'Produkt moc dlouhy',
        slug: '/produkt',
        stock: {
          count: 1,
          created: new Date(),
          id: 'sdfsd',
        },
        price: { discount: null, created: new Date(), id: 'id', value: 100 },
      },
    },
  ],
  state: 'unpaid',
  subtotal: 0,
  telephoneNumber: '',
  delivery_method: {
    created: new Date(),
    description: '',
    id: 'id',
    name: 'Poštou',
    price: 200,
    slug: '/sdfsdf/',
    notes: '',
  },
};
