import {
  OrderDeliveryMethodsSlug,
  OrderPaymentMethodsSlugs,
  OrderState,
  Product,
} from '@najit-najist/database/models';

import { OrderWithRelations } from './types';

const productBase = {
  createdAt: new Date(),
  updatedAt: null,
  categoryId: 4,
  createdById: null,
  onlyForDeliveryMethodId: null,
  publishedAt: null,
  updateById: null,
} satisfies Partial<Product>;

export const testOrder: OrderWithRelations = {
  id: 0,
  userId: 1,
  deliveryMethodId: 1,
  notes: null,
  paymentMethodId: 2,
  telephoneId: 1,
  updatedAt: null,
  discount: 40,
  address: {
    city: 'City',
    houseNumber: '12',
    municipality: {
      name: 'Hradec Kralové',
      slug: 'hradec-kralove',
    },
    postalCode: '50801',
    streetName: 'Jičín',
  },
  createdAt: new Date(),
  email: 'test@example.com',
  firstName: 'Otaka',
  lastName: 'Shimada',
  deliveryMethodPrice: 200,
  paymentMethodPrice: 0,
  couponPatchId: 1,
  couponPatch: {
    reductionPercentage: 0,
    reductionPrice: 40,
    couponId: 1,
    createdAt: new Date(),
    id: 1,
    updatedAt: null,
    coupon: {
      enabled: true,
      createdAt: new Date(),
      id: 1,
      name: 'This is sleva',
      updatedAt: null,
      validFrom: new Date(),
      validTo: null,
      minimalProductCount: 0,
    },
  },
  paymentMethod: {
    description: 'sdfds',
    name: 'Převodem na účet',
    paymentOnCheckout: false,
    slug: OrderPaymentMethodsSlugs.BY_CARD,
    price: 200,
    notes: 'asdfaodsjfoadsjfoasdj',
  },
  orderedProducts: [
    {
      count: 2,
      createdAt: new Date(),
      id: 1,
      orderId: 1,
      productId: 4,
      updatedAt: null,
      totalPrice: 400,
      discount: 0,
      product: {
        ...productBase,
        id: 2,
        images: [],
        name: 'Produkt moc dlouhy',
        slug: '/produkt',
        description: 'Very loooooooong description',
        weight: 0,
        stock: {
          value: 1,
          productId: 2,
        },
        price: { discount: null, value: 100, productId: 2 },
      },
    },
    {
      count: 2,
      createdAt: new Date(),
      id: 3,
      orderId: 1,
      productId: 4,
      updatedAt: null,
      totalPrice: 400,
      discount: 40,
      product: {
        ...productBase,
        id: 4,
        images: [],
        name: 'Produkt moc dlouhy',
        slug: '/produkt',
        description: 'Very loooooooong description',
        stock: {
          value: 1,
          productId: 4,
        },
        weight: 0,
        price: { discount: null, value: 100, productId: 4 },
      },
    },
  ],
  state: OrderState.UNPAID,
  subtotal: 800,
  telephoneNumber: {
    telephone: '12323434',
    code: '420',
  },
  deliveryMethod: {
    description: '',
    name: 'Poštou',
    price: 200,
    slug: OrderDeliveryMethodsSlug.BALIKOVNA,
    notes: '',
  },
};
