export enum ErrorCodes {
  UNABLE_TO_SEND_EMAIL = 'UNABLE_TO_SEND_EMAIL',
  NOT_LOGGED_IN = 'NOT_LOGGED_IN',
  MFA_NOT_LOGGED_IN = 'MFA_NOT_LOGGED_IN',
  WRONG_TOKEN = 'WRONG_TOKEN',
  ENTITY_MISSING = 'ENTITY_MISSING',
  ENTITY_DUPLICATE = 'ENTITY_DUPLICATE',
  EMAIL_ALREADY_SENT = 'EMAIL_ALREADY_SENT',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  USER_CANNOT_LOGIN = 'USER_CANNOT_LOGIN',
  MFA_ALREADY_ACTIVE = 'MFA_ALREADY_ACTIVE',
  GENERIC = 'GENERIC',
}
