version: '3'
services:
  najit-najist-pocketbase:
    build: 
      context: ../../
      dockerfile: apps/pb/Dockerfile
    ports:
      - 8080:8090
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
      - ./migrations:/migrations